<?php
header('Content-Type: text/xml');

echo '<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>Adtodate RSS Document</title>
<link>http://www.adtodate.mk/</link>
<description>RSS document generated by adtodate.mk</description>
<language>mk</language>
<copyright>Copyright 2017 ADTODATE</copyright>
<generator>ADTODATERSS v1.0</generator>
<managingEditor>content@adtodate.mk</managingEditor>';
	$sql = "Select records.id, 
					records.picture, 
					records.create_date, 
					records.edit_date, 
					records.title, 
					records.id_menu, 
					records.text, 
					records.intro, 
					records.publish, 
					records.editor, 
					records.publish_intro,
					_menu.title as _menu_title
			FROM records
			INNER JOIN _menu
            ON records.id_menu=_menu.id
			WHERE publish=1 and editor=1 and id_menu<>15 
			ORDER BY create_date DESC
			LIMIT 0, 20" ;
			//die ($sql);
$con=mysqli_connect("localhost","adtodate_user","67220183122","adtodate_db","3306");
if (mysqli_connect_errno()) {echo "Failed to connect to MySQL: " . mysqli_connect_error();}

$con->query( "SET NAMES 'utf8'");
     	$result_list=mysqli_query($con, $sql);
	//confirm_query($result_list);
	$row_list = mysqli_fetch_assoc($result_list);
	$rowcount1=mysqli_num_rows($result_list);




     mysqli_data_seek($result_list,0);
	 
	      if ($rowcount1==0){echo 'Нема записи...';
       }else{
   
				while($row_list = mysqli_fetch_assoc($result_list)) 
				{  $text=preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $text);
    echo '
       <item>
          <title>'.preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $row_list["title"]).'</title>
          <description>'.preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $row_list["intro"]).'</description> 
		  <category>'.preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $row_list["_menu_title"]).'</category> 
		  <link>http://adtodate.mk/mk/record.php?id='.$row_list["id"].'&#38;mv='.$row_list["id_menu"].'</link>
          <pubDate>' . date("D, d M Y H:i:s O", strtotime($row_list["create_date"])) . '</pubDate>
		  <enclosure type="image/jpeg" url="http://adtodate.mk/uploads/records/'.$row_list["id"].'/tn1_'.preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $row_list["picture"]).'" />
      </item>';
	  
				}
	   }

echo '</channel>
</rss>';
?>